package com.nebulent.dynamo.model;

import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="PassKey")
public class DataModel {

	String PassKeyID;
	Double rangeID;
	String message;
	
	@DynamoDBHashKey(attributeName="PassKeyID")
	@DynamoDBAutoGeneratedKey
	public String getPassKeyID() {
		return PassKeyID;
	}
	public void setPassKeyID(String PassKeyID) {
		this.PassKeyID = PassKeyID;
	}
	
	@DynamoDBRangeKey(attributeName="rangeID")
	public Double getRangeID() {
		return rangeID;
	}
	public void setRangeID(Double rangeID) {
		this.rangeID = rangeID;
	}
	
	@DynamoDBAttribute(attributeName="message")
	public String getMessage() {
		return message;
	}
	
	public void setMessage(String message) {
		this.message = message;
	}
	
	public DataModel() {
		
	}
	
	public DataModel(String message) {
		super();
		this.message = message;
	}
	@Override
	public String toString() {
		return "DataModel [PassKeyID=" + PassKeyID + ", rangeID=" + rangeID
				+ ", message=" + message + "]";
	}
	public DataModel(String passKeyID, Double rangeID) {
		super();
		PassKeyID = passKeyID;
		this.rangeID = rangeID;
	}
	public DataModel(Double rangeID) {
		super();
		this.rangeID = rangeID;
	}
	
	
	
}
