/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package com.nebulent.parsers;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQ = 3;
  /** RegularExpression Id. */
  int NE = 4;
  /** RegularExpression Id. */
  int LT = 5;
  /** RegularExpression Id. */
  int LE = 6;
  /** RegularExpression Id. */
  int GT = 7;
  /** RegularExpression Id. */
  int GE = 8;
  /** RegularExpression Id. */
  int IN = 9;
  /** RegularExpression Id. */
  int BETWEEN = 10;
  /** RegularExpression Id. */
  int SEPARATOR = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int HASHKEY = 13;
  /** RegularExpression Id. */
  int RANGEKEY = 14;
  /** RegularExpression Id. */
  int SIF = 15;
  /** RegularExpression Id. */
  int CONSISTENT = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int HASH = 19;
  /** RegularExpression Id. */
  int NUMBER = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EQ>",
    "<NE>",
    "<LT>",
    "<LE>",
    "<GT>",
    "<GE>",
    "<IN>",
    "<BETWEEN>",
    "\":\"",
    "\",\"",
    "<HASHKEY>",
    "<RANGEKEY>",
    "<SIF>",
    "<CONSISTENT>",
    "<TRUE>",
    "<FALSE>",
    "<HASH>",
    "<NUMBER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
  };

}
