/* Generated By:JavaCC: Do not edit this line. QueryExpressionParserConstants.java */
package com.nebulent.parsers;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQ = 2;
  /** RegularExpression Id. */
  int NE = 3;
  /** RegularExpression Id. */
  int LT = 4;
  /** RegularExpression Id. */
  int LE = 5;
  /** RegularExpression Id. */
  int GT = 6;
  /** RegularExpression Id. */
  int GE = 7;
  /** RegularExpression Id. */
  int IN = 8;
  /** RegularExpression Id. */
  int BETWEEN = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int WORD = 12;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int HASH = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"eq\"",
    "\"ne\"",
    "\"lt\"",
    "\"le\"",
    "\"gt\"",
    "\"ge\"",
    "\"in\"",
    "\"between\"",
    "<NUMBER>",
    "<DIGIT>",
    "<WORD>",
    "<LETTER>",
    "<HASH>",
    "\"(\"",
    "\")\"",
    "\", \"",
  };

}
